moddef::moddef!(
    flat(pub) mod {
        binary,
        debug,
        default,
        display,
        float,
        float_const,
        float_core,
        lower_exp,
        num_,
        num_cast,
        one,
        ops,
        partial_eq,
        partial_ord,
        to_primitive,
        zero,
    }
);