[package]
name = "custom_float"
version = "0.1.2"
edition = "2021"
license = "MIT"
description = "Custom floating-point types"
repository = "https://github.com/sigurd4/custom_float"
keywords = ["float", "number", "custom", "ieee754"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["ethnum"]
ethnum = ["dep:ethnum"]

[dependencies]
array_math = "0.2.16"
moddef = "0.2.2"
num-traits = "0.2.18"
ethnum = {version = "1.5.0", optional = true}

[dev-dependencies]
num = "0.4.1"
